# Generated by Django 3.2.3 on 2022-12-08 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dureeVie', models.IntegerField(auto_created=True, default=5, null=True)),
                ('valinitial', models.IntegerField(auto_created=True, default=500, null=True)),
                ('voiture', models.CharField(max_length=255)),
                ('modele', models.CharField(max_length=255)),
                ('result', models.IntegerField(null=True)),
                ('dureePasse', models.IntegerField(default=0, null=True)),
                ('anneeAchat', models.DateField(null=True)),
                ('matercule', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicule')),
            ],
        ),
    ]
