# Generated by Django 3.2.3 on 2022-12-06 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicule')),
            ],
        ),
    ]
