# Generated by Django 3.2.3 on 2022-12-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_anneeachat_vehicule_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='date',
            new_name='dateAmortissement',
        ),
        migrations.RenameField(
            model_name='vehicule',
            old_name='dureeVie',
            new_name='dureeAmortisssement',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='result',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='valresudiel',
            field=models.IntegerField(auto_created=True, default=10, null=True),
        ),
    ]
