# Generated by Django 3.2.3 on 2022-12-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20221208_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='amortissement',
            field=models.IntegerField(null=True),
        ),
    ]
